### ISSUE TITLE
Does not compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by skycanine** [mkrufky/libdvbtee#54]
commit ea75b569d8d63ede90f042def36628dcf913271d (HEAD -> master, tag: v0.6.7, origin/master, origin/HEAD)

```
In file included from decoder.cpp:22:0:                                                                                                                                                             
decoder.h:33:10: fatal error: dvbpsi/dvbpsi.h: No such file or directory                                                                                                                            
 #include "dvbpsi/dvbpsi.h"       
```

```
hdhr_tuner.cpp:31:10: fatal error: hdhomerun.h: No such file or directory                             
 #include "hdhomerun.h"    
```

**Comment by mkrufky** [comment]
If you want to control an HdHomerun device, then you will need to install `libhdhomerun-dev` before running any of libdvbtee's build scripts.

After doing so, the `configure` script will configure the build system to use either an HdHomerun device, a LinuxTV device, or no device at all.

libdvbtee uses a custom version of libdvbpsi, and the `build-auto.sh` script takes care of that for you, along with the configuration and build.

Please try again using the `build-auto.sh` script.

**Comment by skycanine** [comment]
Ahh, thanks.  I'll try again when I get a chance.  

I've written a PVR for HDHomerun.  A user clicks on "Record" in a TitanTV.com tv guide.  That Downloads a program.tvpi file which I've associated with a bash script.  It adds a cron job which calls the same bash script, but to record the show.  The recording functions call APIs to flesh out the show/movie title in the Plex naming convention.  I'd like to improve its repeat recording feature which currently assumes the same weekday and time.  So a correct local tv guide is important.  I hope your library can help me there.  Thanks!

**Comment by skycanine** [comment]
Below makes the compile succeed.

[Previously installed libhdhomerun](https://www.silicondust.com/support/linux/)

```
sudo cp -p libhdhomerun/*.h /usr/include/libhdhomerun/ # of course, do mkdir and chmod
```
